export const etapasData = [
  { etapa: "Con Acceso por Tribunales", cantidad: 5 },
  { etapa: "Con Convenio Aprobado sin Enviar a Fiscalía", cantidad: 12 },
  { etapa: "Convenio Complementario en trámite", cantidad: 8 },
  { etapa: "Convenio Complementario Finalizado Inscr. y Pag.", cantidad: 6 },
  { etapa: "Convenio Decretado", cantidad: 9 },
  { etapa: "Convenio enviado a Fiscalía", cantidad: 11 },
  { etapa: "Convenio Finalizado Inscr. y Pag.", cantidad: 14 },
  { etapa: "Convenio Inscrito sin pagar", cantidad: 7 },
  { etapa: "Con Convenio Objetado", cantidad: 4 },
  { etapa: "Con Convenio recibido en Revisión", cantidad: 10 },
  { etapa: "Convenio Publicado", cantidad: 13 },
  { etapa: "Convenio sin Antecedentes UTE", cantidad: 3 },
  { etapa: "Revisado en Convenio enviado a VJ", cantidad: 5 },
  { etapa: "Fuera de proceso expropiatorio", cantidad: 2 },
  { etapa: "Terreno Fiscal", cantidad: 15 },
  { etapa: "Terreno con Patrimonio de afectación Fiscal", cantidad: 6 },
  { etapa: "Finalizado sin Antecedentes Completos", cantidad: 4 },
  { etapa: "VJ Consignado", cantidad: 9 },
  { etapa: "VJ Decretado", cantidad: 10 },
  { etapa: "VJ enviado a Fiscalía", cantidad: 8 },
  { etapa: "Judicial Finalizado inscrito Fisco", cantidad: 5 },
  { etapa: "VJ con TPM proveída", cantidad: 7 },
  { etapa: "VJ Publicado", cantidad: 6 },
  { etapa: "Vía Judicial sin Enviar a Trámite", cantidad: 4 },
  { etapa: "Notificado sin Definir Vía", cantidad: 3 },
  { etapa: "Adquirido por SC", cantidad: 2 },
  { etapa: "Donación", cantidad: 1 },
  { etapa: "Enajenación por Compensación", cantidad: 3 },
  { etapa: "Servidumbre", cantidad: 2 },
  { etapa: "Planos Aprobados sin Firma IF", cantidad: 9 },
  { etapa: "Planos en Corrección en Consultora o Concesionaria", cantidad: 6 },
  { etapa: "Planos en Corrección por Vuelta atrás", cantidad: 4 },
  { etapa: "Plano Definitivo sin Enviar a Tasar", cantidad: 7 },
  { etapa: "Planos en Elaboración en la UTE", cantidad: 10 },
  { etapa: "Planos en Modificación de Proyecto", cantidad: 5 },
  { etapa: "Planos en Revisión", cantidad: 8 },
  { etapa: "Stand By", cantidad: 3 },
  { etapa: "Sentencia Judicial (art. 9) en trámite", cantidad: 2 },
  { etapa: "Tasado", cantidad: 11 },
  { etapa: "Tasaciones Aprobadas sin enviar a Jurídica", cantidad: 4 },
  { etapa: "En Tasación", cantidad: 7 },
  { etapa: "Tasaciones detenidas por Modificaciones de Proyecto", cantidad: 5 },
  { etapa: "Tasándose sin Plano Definitivo", cantidad: 3 },
  { etapa: "Vías Paralelas", cantidad: 2 },
];
