/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedFormulariosRouteImport } from './routes/_authenticated/formularios'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedFormulariosIndexRouteImport } from './routes/_authenticated/formularios/index'
import { Route as AuthenticatedReportesTasadoresRouteImport } from './routes/_authenticated/reportes/tasadores'
import { Route as AuthenticatedReportesPeritosComisionRouteImport } from './routes/_authenticated/reportes/peritos-comision'
import { Route as AuthenticatedReportesPeritosBoletasRouteImport } from './routes/_authenticated/reportes/peritos-boletas'
import { Route as AuthenticatedReportesLotesComisionRouteImport } from './routes/_authenticated/reportes/lotes-comision'
import { Route as AuthenticatedReportesLotesRouteImport } from './routes/_authenticated/reportes/lotes'
import { Route as AuthenticatedReportesIngTasadoresRouteImport } from './routes/_authenticated/reportes/ing-tasadores'
import { Route as AuthenticatedReportesEstReclamosRouteImport } from './routes/_authenticated/reportes/est-reclamos'
import { Route as AuthenticatedReportesDetalleReclamoElimRouteImport } from './routes/_authenticated/reportes/detalle-reclamo-elim'
import { Route as AuthenticatedReportesDetalleReclamoRouteImport } from './routes/_authenticated/reportes/detalle-reclamo'
import { Route as AuthenticatedReportesDesgloseTasRouteImport } from './routes/_authenticated/reportes/desglose-tas'
import { Route as AuthenticatedReportesComisionesRouteImport } from './routes/_authenticated/reportes/comisiones'
import { Route as AuthenticatedFormulariosTipoRouteImport } from './routes/_authenticated/formularios/$tipo'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminActivity_logsRouteImport } from './routes/_authenticated/admin/activity_logs'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormulariosRoute =
  AuthenticatedFormulariosRouteImport.update({
    id: '/formularios',
    path: '/formularios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormulariosIndexRoute =
  AuthenticatedFormulariosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFormulariosRoute,
  } as any)
const AuthenticatedReportesTasadoresRoute =
  AuthenticatedReportesTasadoresRouteImport.update({
    id: '/tasadores',
    path: '/tasadores',
    getParentRoute: () => AuthenticatedReportesRoute,
  } as any)
const AuthenticatedReportesPeritosComisionRoute =
  AuthenticatedReportesPeritosComisionRouteImport.update({
    id: '/peritos-comision',
    path: '/peritos-comision',
    getParentRoute: () => AuthenticatedReportesRoute,
  } as any)
const AuthenticatedReportesPeritosBoletasRoute =
  AuthenticatedReportesPeritosBoletasRouteImport.update({
    id: '/peritos-boletas',
    path: '/peritos-boletas',
    getParentRoute: () => AuthenticatedReportesRoute,
  } as any)
const AuthenticatedReportesLotesComisionRoute =
  AuthenticatedReportesLotesComisionRouteImport.update({
    id: '/lotes-comision',
    path: '/lotes-comision',
    getParentRoute: () => AuthenticatedReportesRoute,
  } as any)
const AuthenticatedReportesLotesRoute =
  AuthenticatedReportesLotesRouteImport.update({
    id: '/lotes',
    path: '/lotes',
    getParentRoute: () => AuthenticatedReportesRoute,
  } as any)
const AuthenticatedReportesIngTasadoresRoute =
  AuthenticatedReportesIngTasadoresRouteImport.update({
    id: '/ing-tasadores',
    path: '/ing-tasadores',
    getParentRoute: () => AuthenticatedReportesRoute,
  } as any)
const AuthenticatedReportesEstReclamosRoute =
  AuthenticatedReportesEstReclamosRouteImport.update({
    id: '/est-reclamos',
    path: '/est-reclamos',
    getParentRoute: () => AuthenticatedReportesRoute,
  } as any)
const AuthenticatedReportesDetalleReclamoElimRoute =
  AuthenticatedReportesDetalleReclamoElimRouteImport.update({
    id: '/detalle-reclamo-elim',
    path: '/detalle-reclamo-elim',
    getParentRoute: () => AuthenticatedReportesRoute,
  } as any)
const AuthenticatedReportesDetalleReclamoRoute =
  AuthenticatedReportesDetalleReclamoRouteImport.update({
    id: '/detalle-reclamo',
    path: '/detalle-reclamo',
    getParentRoute: () => AuthenticatedReportesRoute,
  } as any)
const AuthenticatedReportesDesgloseTasRoute =
  AuthenticatedReportesDesgloseTasRouteImport.update({
    id: '/desglose-tas',
    path: '/desglose-tas',
    getParentRoute: () => AuthenticatedReportesRoute,
  } as any)
const AuthenticatedReportesComisionesRoute =
  AuthenticatedReportesComisionesRouteImport.update({
    id: '/comisiones',
    path: '/comisiones',
    getParentRoute: () => AuthenticatedReportesRoute,
  } as any)
const AuthenticatedFormulariosTipoRoute =
  AuthenticatedFormulariosTipoRouteImport.update({
    id: '/$tipo',
    path: '/$tipo',
    getParentRoute: () => AuthenticatedFormulariosRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivity_logsRoute =
  AuthenticatedAdminActivity_logsRouteImport.update({
    id: '/activity_logs',
    path: '/activity_logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/formularios': typeof AuthenticatedFormulariosRouteWithChildren
  '/reportes': typeof AuthenticatedReportesRouteWithChildren
  '/admin/activity_logs': typeof AuthenticatedAdminActivity_logsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/formularios/$tipo': typeof AuthenticatedFormulariosTipoRoute
  '/reportes/comisiones': typeof AuthenticatedReportesComisionesRoute
  '/reportes/desglose-tas': typeof AuthenticatedReportesDesgloseTasRoute
  '/reportes/detalle-reclamo': typeof AuthenticatedReportesDetalleReclamoRoute
  '/reportes/detalle-reclamo-elim': typeof AuthenticatedReportesDetalleReclamoElimRoute
  '/reportes/est-reclamos': typeof AuthenticatedReportesEstReclamosRoute
  '/reportes/ing-tasadores': typeof AuthenticatedReportesIngTasadoresRoute
  '/reportes/lotes': typeof AuthenticatedReportesLotesRoute
  '/reportes/lotes-comision': typeof AuthenticatedReportesLotesComisionRoute
  '/reportes/peritos-boletas': typeof AuthenticatedReportesPeritosBoletasRoute
  '/reportes/peritos-comision': typeof AuthenticatedReportesPeritosComisionRoute
  '/reportes/tasadores': typeof AuthenticatedReportesTasadoresRoute
  '/formularios/': typeof AuthenticatedFormulariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reportes': typeof AuthenticatedReportesRouteWithChildren
  '/admin/activity_logs': typeof AuthenticatedAdminActivity_logsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/formularios/$tipo': typeof AuthenticatedFormulariosTipoRoute
  '/reportes/comisiones': typeof AuthenticatedReportesComisionesRoute
  '/reportes/desglose-tas': typeof AuthenticatedReportesDesgloseTasRoute
  '/reportes/detalle-reclamo': typeof AuthenticatedReportesDetalleReclamoRoute
  '/reportes/detalle-reclamo-elim': typeof AuthenticatedReportesDetalleReclamoElimRoute
  '/reportes/est-reclamos': typeof AuthenticatedReportesEstReclamosRoute
  '/reportes/ing-tasadores': typeof AuthenticatedReportesIngTasadoresRoute
  '/reportes/lotes': typeof AuthenticatedReportesLotesRoute
  '/reportes/lotes-comision': typeof AuthenticatedReportesLotesComisionRoute
  '/reportes/peritos-boletas': typeof AuthenticatedReportesPeritosBoletasRoute
  '/reportes/peritos-comision': typeof AuthenticatedReportesPeritosComisionRoute
  '/reportes/tasadores': typeof AuthenticatedReportesTasadoresRoute
  '/formularios': typeof AuthenticatedFormulariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/formularios': typeof AuthenticatedFormulariosRouteWithChildren
  '/_authenticated/reportes': typeof AuthenticatedReportesRouteWithChildren
  '/_authenticated/admin/activity_logs': typeof AuthenticatedAdminActivity_logsRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/formularios/$tipo': typeof AuthenticatedFormulariosTipoRoute
  '/_authenticated/reportes/comisiones': typeof AuthenticatedReportesComisionesRoute
  '/_authenticated/reportes/desglose-tas': typeof AuthenticatedReportesDesgloseTasRoute
  '/_authenticated/reportes/detalle-reclamo': typeof AuthenticatedReportesDetalleReclamoRoute
  '/_authenticated/reportes/detalle-reclamo-elim': typeof AuthenticatedReportesDetalleReclamoElimRoute
  '/_authenticated/reportes/est-reclamos': typeof AuthenticatedReportesEstReclamosRoute
  '/_authenticated/reportes/ing-tasadores': typeof AuthenticatedReportesIngTasadoresRoute
  '/_authenticated/reportes/lotes': typeof AuthenticatedReportesLotesRoute
  '/_authenticated/reportes/lotes-comision': typeof AuthenticatedReportesLotesComisionRoute
  '/_authenticated/reportes/peritos-boletas': typeof AuthenticatedReportesPeritosBoletasRoute
  '/_authenticated/reportes/peritos-comision': typeof AuthenticatedReportesPeritosComisionRoute
  '/_authenticated/reportes/tasadores': typeof AuthenticatedReportesTasadoresRoute
  '/_authenticated/formularios/': typeof AuthenticatedFormulariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/formularios'
    | '/reportes'
    | '/admin/activity_logs'
    | '/admin/usuarios'
    | '/formularios/$tipo'
    | '/reportes/comisiones'
    | '/reportes/desglose-tas'
    | '/reportes/detalle-reclamo'
    | '/reportes/detalle-reclamo-elim'
    | '/reportes/est-reclamos'
    | '/reportes/ing-tasadores'
    | '/reportes/lotes'
    | '/reportes/lotes-comision'
    | '/reportes/peritos-boletas'
    | '/reportes/peritos-comision'
    | '/reportes/tasadores'
    | '/formularios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/reportes'
    | '/admin/activity_logs'
    | '/admin/usuarios'
    | '/formularios/$tipo'
    | '/reportes/comisiones'
    | '/reportes/desglose-tas'
    | '/reportes/detalle-reclamo'
    | '/reportes/detalle-reclamo-elim'
    | '/reportes/est-reclamos'
    | '/reportes/ing-tasadores'
    | '/reportes/lotes'
    | '/reportes/lotes-comision'
    | '/reportes/peritos-boletas'
    | '/reportes/peritos-comision'
    | '/reportes/tasadores'
    | '/formularios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/formularios'
    | '/_authenticated/reportes'
    | '/_authenticated/admin/activity_logs'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/formularios/$tipo'
    | '/_authenticated/reportes/comisiones'
    | '/_authenticated/reportes/desglose-tas'
    | '/_authenticated/reportes/detalle-reclamo'
    | '/_authenticated/reportes/detalle-reclamo-elim'
    | '/_authenticated/reportes/est-reclamos'
    | '/_authenticated/reportes/ing-tasadores'
    | '/_authenticated/reportes/lotes'
    | '/_authenticated/reportes/lotes-comision'
    | '/_authenticated/reportes/peritos-boletas'
    | '/_authenticated/reportes/peritos-comision'
    | '/_authenticated/reportes/tasadores'
    | '/_authenticated/formularios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formularios': {
      id: '/_authenticated/formularios'
      path: '/formularios'
      fullPath: '/formularios'
      preLoaderRoute: typeof AuthenticatedFormulariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formularios/': {
      id: '/_authenticated/formularios/'
      path: '/'
      fullPath: '/formularios/'
      preLoaderRoute: typeof AuthenticatedFormulariosIndexRouteImport
      parentRoute: typeof AuthenticatedFormulariosRoute
    }
    '/_authenticated/reportes/tasadores': {
      id: '/_authenticated/reportes/tasadores'
      path: '/tasadores'
      fullPath: '/reportes/tasadores'
      preLoaderRoute: typeof AuthenticatedReportesTasadoresRouteImport
      parentRoute: typeof AuthenticatedReportesRoute
    }
    '/_authenticated/reportes/peritos-comision': {
      id: '/_authenticated/reportes/peritos-comision'
      path: '/peritos-comision'
      fullPath: '/reportes/peritos-comision'
      preLoaderRoute: typeof AuthenticatedReportesPeritosComisionRouteImport
      parentRoute: typeof AuthenticatedReportesRoute
    }
    '/_authenticated/reportes/peritos-boletas': {
      id: '/_authenticated/reportes/peritos-boletas'
      path: '/peritos-boletas'
      fullPath: '/reportes/peritos-boletas'
      preLoaderRoute: typeof AuthenticatedReportesPeritosBoletasRouteImport
      parentRoute: typeof AuthenticatedReportesRoute
    }
    '/_authenticated/reportes/lotes-comision': {
      id: '/_authenticated/reportes/lotes-comision'
      path: '/lotes-comision'
      fullPath: '/reportes/lotes-comision'
      preLoaderRoute: typeof AuthenticatedReportesLotesComisionRouteImport
      parentRoute: typeof AuthenticatedReportesRoute
    }
    '/_authenticated/reportes/lotes': {
      id: '/_authenticated/reportes/lotes'
      path: '/lotes'
      fullPath: '/reportes/lotes'
      preLoaderRoute: typeof AuthenticatedReportesLotesRouteImport
      parentRoute: typeof AuthenticatedReportesRoute
    }
    '/_authenticated/reportes/ing-tasadores': {
      id: '/_authenticated/reportes/ing-tasadores'
      path: '/ing-tasadores'
      fullPath: '/reportes/ing-tasadores'
      preLoaderRoute: typeof AuthenticatedReportesIngTasadoresRouteImport
      parentRoute: typeof AuthenticatedReportesRoute
    }
    '/_authenticated/reportes/est-reclamos': {
      id: '/_authenticated/reportes/est-reclamos'
      path: '/est-reclamos'
      fullPath: '/reportes/est-reclamos'
      preLoaderRoute: typeof AuthenticatedReportesEstReclamosRouteImport
      parentRoute: typeof AuthenticatedReportesRoute
    }
    '/_authenticated/reportes/detalle-reclamo-elim': {
      id: '/_authenticated/reportes/detalle-reclamo-elim'
      path: '/detalle-reclamo-elim'
      fullPath: '/reportes/detalle-reclamo-elim'
      preLoaderRoute: typeof AuthenticatedReportesDetalleReclamoElimRouteImport
      parentRoute: typeof AuthenticatedReportesRoute
    }
    '/_authenticated/reportes/detalle-reclamo': {
      id: '/_authenticated/reportes/detalle-reclamo'
      path: '/detalle-reclamo'
      fullPath: '/reportes/detalle-reclamo'
      preLoaderRoute: typeof AuthenticatedReportesDetalleReclamoRouteImport
      parentRoute: typeof AuthenticatedReportesRoute
    }
    '/_authenticated/reportes/desglose-tas': {
      id: '/_authenticated/reportes/desglose-tas'
      path: '/desglose-tas'
      fullPath: '/reportes/desglose-tas'
      preLoaderRoute: typeof AuthenticatedReportesDesgloseTasRouteImport
      parentRoute: typeof AuthenticatedReportesRoute
    }
    '/_authenticated/reportes/comisiones': {
      id: '/_authenticated/reportes/comisiones'
      path: '/comisiones'
      fullPath: '/reportes/comisiones'
      preLoaderRoute: typeof AuthenticatedReportesComisionesRouteImport
      parentRoute: typeof AuthenticatedReportesRoute
    }
    '/_authenticated/formularios/$tipo': {
      id: '/_authenticated/formularios/$tipo'
      path: '/$tipo'
      fullPath: '/formularios/$tipo'
      preLoaderRoute: typeof AuthenticatedFormulariosTipoRouteImport
      parentRoute: typeof AuthenticatedFormulariosRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity_logs': {
      id: '/_authenticated/admin/activity_logs'
      path: '/activity_logs'
      fullPath: '/admin/activity_logs'
      preLoaderRoute: typeof AuthenticatedAdminActivity_logsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivity_logsRoute: typeof AuthenticatedAdminActivity_logsRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivity_logsRoute: AuthenticatedAdminActivity_logsRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedFormulariosRouteChildren {
  AuthenticatedFormulariosTipoRoute: typeof AuthenticatedFormulariosTipoRoute
  AuthenticatedFormulariosIndexRoute: typeof AuthenticatedFormulariosIndexRoute
}

const AuthenticatedFormulariosRouteChildren: AuthenticatedFormulariosRouteChildren =
  {
    AuthenticatedFormulariosTipoRoute: AuthenticatedFormulariosTipoRoute,
    AuthenticatedFormulariosIndexRoute: AuthenticatedFormulariosIndexRoute,
  }

const AuthenticatedFormulariosRouteWithChildren =
  AuthenticatedFormulariosRoute._addFileChildren(
    AuthenticatedFormulariosRouteChildren,
  )

interface AuthenticatedReportesRouteChildren {
  AuthenticatedReportesComisionesRoute: typeof AuthenticatedReportesComisionesRoute
  AuthenticatedReportesDesgloseTasRoute: typeof AuthenticatedReportesDesgloseTasRoute
  AuthenticatedReportesDetalleReclamoRoute: typeof AuthenticatedReportesDetalleReclamoRoute
  AuthenticatedReportesDetalleReclamoElimRoute: typeof AuthenticatedReportesDetalleReclamoElimRoute
  AuthenticatedReportesEstReclamosRoute: typeof AuthenticatedReportesEstReclamosRoute
  AuthenticatedReportesIngTasadoresRoute: typeof AuthenticatedReportesIngTasadoresRoute
  AuthenticatedReportesLotesRoute: typeof AuthenticatedReportesLotesRoute
  AuthenticatedReportesLotesComisionRoute: typeof AuthenticatedReportesLotesComisionRoute
  AuthenticatedReportesPeritosBoletasRoute: typeof AuthenticatedReportesPeritosBoletasRoute
  AuthenticatedReportesPeritosComisionRoute: typeof AuthenticatedReportesPeritosComisionRoute
  AuthenticatedReportesTasadoresRoute: typeof AuthenticatedReportesTasadoresRoute
}

const AuthenticatedReportesRouteChildren: AuthenticatedReportesRouteChildren = {
  AuthenticatedReportesComisionesRoute: AuthenticatedReportesComisionesRoute,
  AuthenticatedReportesDesgloseTasRoute: AuthenticatedReportesDesgloseTasRoute,
  AuthenticatedReportesDetalleReclamoRoute:
    AuthenticatedReportesDetalleReclamoRoute,
  AuthenticatedReportesDetalleReclamoElimRoute:
    AuthenticatedReportesDetalleReclamoElimRoute,
  AuthenticatedReportesEstReclamosRoute: AuthenticatedReportesEstReclamosRoute,
  AuthenticatedReportesIngTasadoresRoute:
    AuthenticatedReportesIngTasadoresRoute,
  AuthenticatedReportesLotesRoute: AuthenticatedReportesLotesRoute,
  AuthenticatedReportesLotesComisionRoute:
    AuthenticatedReportesLotesComisionRoute,
  AuthenticatedReportesPeritosBoletasRoute:
    AuthenticatedReportesPeritosBoletasRoute,
  AuthenticatedReportesPeritosComisionRoute:
    AuthenticatedReportesPeritosComisionRoute,
  AuthenticatedReportesTasadoresRoute: AuthenticatedReportesTasadoresRoute,
}

const AuthenticatedReportesRouteWithChildren =
  AuthenticatedReportesRoute._addFileChildren(
    AuthenticatedReportesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFormulariosRoute: typeof AuthenticatedFormulariosRouteWithChildren
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFormulariosRoute: AuthenticatedFormulariosRouteWithChildren,
  AuthenticatedReportesRoute: AuthenticatedReportesRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
